version: 2
jobs:
  "deploy_delivery_gcf":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-latest-node-with-gcloud:0.0.1

    steps:
      - checkout
      - run: git checkout origin/configuration/delivery -- config.js
      - run: &GCLOUDAUTH
          name: GCLOUD Authentication
          command: |
            echo $GCLOUD_AUTH_BASE64| base64 --decode > ./creds.json
            gcloud auth activate-service-account --key-file=./creds.json
            gcloud config set project $DEPLOY_PROJECT_ID

      - run:
          name: Deploy GCF
          command: |
            npm run prepare
            gsutil cp deploy.zip gs://client-side-events-gcf-staging-bucket/${CIRCLE_JOB}${CIRCLE_BUILD_NUM}.zip
            gcloud functions deploy populate-delivery-kpis --entry-point=runPubSub --memory=256MB --runtime=nodejs10 --timeout=180s --source=gs://client-side-events-gcf-staging-bucket/${CIRCLE_JOB}${CIRCLE_BUILD_NUM}.zip

  "something_else":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - run: git checkout origin/configuration/some-other -- config.js
      - run: *GCLOUDAUTH
      - run:
          name: Deploy GCF
          command: |
            npm run prepare
            gsutil cp deploy.zip gs://client-side-events-gcf-staging-bucket/${CIRCLE_JOB}${CIRCLE_BUILD_NUM}.zip
            gcloud functions deploy some_other-gcf --entry-point=runPubSub --memory=256MB --runtime=nodejs10 --timeout=180s --source=gs://client-side-events-gcf-staging-bucket/${CIRCLE_JOB}${CIRCLE_BUILD_NUM}.zip

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - "deploy_delivery_gcf":
          filters:
            branches:
              only:
                - master
                - configuration/delivery
      - "something_else":
          filters:
            branches:
              only:
                - notusedyet
